pull_request_rules:
  - name: Auto merge for code changed
    conditions:
      - base=master
      - -title~=(?i)\[wip\]
      - "status-success=Code Checker AMD64 Ubuntu 18.04"
      - "status-success=Build and test AMD64 Ubuntu 18.04"
      - "status-success=continuous-integration/jenkins/pr-merge"
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - -title~=(?i)\[wip\]
      - -body~=^[^\n]{72,}$
      - "status-success=DCO"
      - -label=PR | manual merge
    actions:
      merge:
        method: squash
        commit_message: title+body

  - name: Auto merge for document changed
    conditions:
      - base=master
      - -files~=\.(?!md|png)
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - -body~=^[^\n]{72,}$
      - -title~=(?i)\[wip\]
      - "status-success=DCO"
      - -label=PR | manual merge
    actions:
      merge:
        method: squash
        commit_message: title+body

  - name: Warn on width limit exceeded
    conditions:
      - base=master
      - body~=^[^\n]{72,}$
    actions:
        comment:
            message: |
                The pull request body line width exceeded limit. Could you fix it @{{author}}?

  - name: Warn on conflict
    conditions:
      - base=master
      - conflict
    actions:
        comment:
            message: |
                This pull request is now in conflicts. Could you fix it @{{author}}? 🙏

  - name: Warn on DCO failed
    conditions:
      - base=master
      - -status-success=DCO
    actions:
        comment:
            message: |
                DCO check failed. Could you fix it @{{author}}? 🙏

